[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
# Web service
actix-web = "4"
utoipa = { version = "5", features = ["actix_extras"] }
utoipa-swagger-ui = { version = "9", features = ["actix-web"] }
# JSON
serde_json = "1.0"
# Logging
env_logger = "0.11"